services:
  pytorch-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pytorch-learning-env
    ports:
      - "8888:8888" # Jupyter notebook port
      - "6006:6006" # TensorBoard port (optional)
    volumes:
      # Mount the entire features directory - automatically includes all feature subdirectories
      - ./features:/workspace/features
      # Jupyter configuration
      - ./jupyter_server_config.py:/root/.jupyter/jupyter_server_config.py
    environment:
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /workspace
    command: >
      bash -c "
        jupyter lab --config=/root/.jupyter/jupyter_server_config.py
      "
    restart: unless-stopped
    # Note: NVIDIA GPU support is not available on Apple Silicon (M1/M2/M3)
    # Apple Silicon uses MPS (Metal Performance Shaders) for GPU acceleration
    # MPS support is built into PyTorch and doesn't require special Docker configuration

networks:
  default:
    name: pytorch-network
